### PR TITLE
Add fr-ON language to config

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
Add fr-ON language to config

FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux

### CODE REVIEW

**Comment by Vitalii-Misechko** [comment]
@johngwilkinson, @dlockhart could you review PR?

**Review by dlockhart — APPROVED** [review]

**Comment by Vitalii-Misechko** [comment]
Unfortunately, I can't merge this PR due to I have no write access. Feel free to merge it.

image

**Review by johngwilkinson — APPROVED** [review]
I can't merge it either

**Comment by Vitalii-Misechko** [comment]
Oh...and after the merge, we'd like to release the new version I guess. 

@dlockhart, could you provide access to us OR just merge and release?

**Comment by dlockhart** [comment]
I don't think this is going to release properly (it's been multiple years). I'll migrate to GitHub Actions right now.

**Pull request merged**
