### PR TITLE
Add cy-GB, es-ES, fr-FR languages to config.js

### PR DESCRIPTION
**Pull request by TarasShDev**
Add **cy-GB**, **es-ES**, **fr-FR** language to config.js
Our `DataHub` app has language packages for [cy-GB](https://github.com/Brightspace/datahub/blob/master/src/lang/cy-gb.json), [es-ES](https://github.com/Brightspace/datahub/blob/master/src/lang/es-es.json) and [fr-FR](https://github.com/Brightspace/datahub/blob/master/src/lang/fr-fr.json) that are not supported by `frau-locale-provider`.

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]

**Review by neverendingqs — APPROVED** [review]
LGTM. Disclaimer: this is unfamiliar territory for me.

**Comment by TarasShDev** [comment]
@dlockhart I've merged it, but how can we update the version (I thought it works automatically)?

**Comment by TarasShDev** [comment]
@dlockhart how can we release these changes?

**Comment by dlockhart** [comment]
You would have [needed to include "feat:" in the merge commit](https://github.com/Brightspace/frau-locale-provider#versioning--releasing) to release.

**Comment by DonBrinn** [comment]
Would a new no-op PR with a PR title starting with "feat: " be adequate to tripper the release when merged?

**Comment by dlockhart** [comment]
Yep that'll work!

**Pull request merged**
